mkdir data/
cd data
wget http://mapbox-geodata.s3.amazonaws.com/natural-earth-1.4.0/cultural/10m-admin-0-countries.zip
unp *.zip
rm *.zip
cd ..
cd layers
wget https://wildfire.cr.usgs.gov/firehistory/data/wf_all_1980_2016.zip
unp *.zip
rm *.zip
cd ..